### ISSUE TITLE
Lab does not require use of map

### ISSUE THREAD

**Issue by Denbox** [learn-co-curriculum/js-looping-and-iteration-map-lab#5]
Students can pass this lab without using map, because the function is not required in `indexTest.js`.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback @Denbox.

We have updated the materials to test for the use of .map in each function and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
